"""activities and subjects tables

Revision ID: 65b0d3104bc8
Revises: f36a27e99c8d
Create Date: 2025-12-25 21:14:52.785726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b0d3104bc8'
down_revision: Union[str, Sequence[str], None] = 'f36a27e99c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subject_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=True),
    sa.Column('max_progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_activity_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.add_column('users', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('group_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'group_name')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    # ### end Alembic commands ###
